# Generated by Django 3.1.3 on 2020-11-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=30, null=True)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('event_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('event_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
