# Generated by Django 3.1.3 on 2020-11-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/events'),
        ),
    ]
