# Generated by Django 3.1.3 on 2020-11-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20201117_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
