# Generated by Django 3.1.3 on 2021-02-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_event_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='event_datetime_begin',
        ),
        migrations.AddField(
            model_name='event',
            name='event_datetime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
