# Generated by Django 3.1.3 on 2021-02-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210208_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_datetime_begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_organizer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventtouser',
            name='status',
            field=models.CharField(choices=[('event_organizer', 'Organizer'), ('to_visit', 'To visit'), ('visited', 'Visited')], max_length=20, null=True),
        ),
    ]
