# Generated by Django 3.1.3 on 2021-02-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210208_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtouser',
            name='event_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eventtouser',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
