# Generated by Django 3.1.3 on 2020-11-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0004_auto_20201114_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pets',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Single'), (1, 'In relationship'), (2, 'Married')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
    ]
