# Generated by Django 3.1.3 on 2020-11-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0005_auto_20201116_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organizer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
