# Generated by Django 3.1.3 on 2020-11-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0006_auto_20201117_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
