# Generated by Django 3.1.3 on 2020-11-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0007_user_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rating',
            new_name='user_rating',
        ),
    ]
