# Generated by Django 3.1.3 on 2020-11-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0008_auto_20201125_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_rating',
        ),
    ]
