# Generated by Django 3.1.3 on 2020-11-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0009_remove_user_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pets',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
