# Generated by Django 3.1.3 on 2021-01-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0011_auto_20201206_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
