# Generated by Django 3.1.3 on 2021-02-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0012_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('not_specified', 'Not specified'), ('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
    ]
