# Generated by Django 3.1.3 on 2021-02-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0013_auto_20210206_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/user_photos'),
        ),
    ]
