# Generated by Django 3.1.3 on 2021-02-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0014_auto_20210208_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
